name: lastfm_sentiment_umap_24
channels:
  - aibox
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.14
  - recbole
  - torchaudio
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - numpy=1.25.2
  - numpy-base=1.25.2
  - pandas=1.5.3
